### ISSUE TITLE
delete-all-and-exit doesn't actually delete orders for ccxt-coinbasepro, and triggers early

### ISSUE THREAD

**Issue by Reidmcc** [stellar/kelp#150]
## Describe the bug
When the delete-all-and-exit action is triggered by exceeding `DELETE_CYCLES_THRESHOLD` when trading on ccxt-coinbasepro, Kelp doesn't actually delete the orders. It is also triggering when it should not. In the attached log I have `DELETE_CYCLES_THRESHOLD` set to 1000 as a test and it promptly errors out. With `FILL_TRACKER_SLEEP_MILLIS` set to 5000 and `TICK_INTERVAL_SECONDS` set to 60 it shouldn't even be possible to trigger that threshold.

## Expected behavior
Kelp should exit and delete orders as configured.

## Frequency
It happens every time a ccxt-coinbasepro ticker check times out, at the least.

## Steps To Reproduce
1. Set Kelp to trade on ccxt-coinbasepro and also use a pricefeed from ccxt-coinbasepro. 
2. Wait for a ticker check to time out.

## Possible Solution
I don't know why this happens.

## Your Environment
version: buysell-mod:v1.6.0-3-g86930f98-dirty
git branch: buysell-mod
git hash: 86930f9-dirty
build date: 20190401T004255Z
GOOS: linux
GOARCH: amd64

## Context
I have to set `DELETE_CYCLES_THRESHOLD` to -1 to trade on ccxt-coinbasepro and forgo the order deletion safety feature.

## Attachments
[delete_all_failure_example.log](https://github.com/stellar/kelp/files/3046167/delete_all_failure_example.log)

**Comment by Reidmcc** [comment]
Kelp is not respecting `DELETE_CYCLES_THRESHOLD` at all. It's exiting after one error even if set to -1, see attached log.
[log_XLM_USD_20190407T202628UTC.log](https://github.com/stellar/kelp/files/3052112/log_XLM_USD_20190407T202628UTC.log)

**Comment by nikhilsaraf** [comment]
@Reidmcc this was triggered because your `FILL_TRACKER_DELETE_CYCLES_THRESHOLD` was set to `0`.

see the error message which points this out:
`deleting all offers, num. continuous fill tracking cycles with errors (including this one): 1; (fillTrackerDeleteCyclesThreshold to be exceeded=0)`

This occurs when the fill tracker encounters an error. If you increase this threshold it should fix the issue.

It can be a bit confusing since `FILL_TRACKER_DELETE_CYCLES_THRESHOLD` is very similar to `DELETE_CYCLES_THRESHOLD`.

**Comment by Reidmcc** [comment]
@nikhilsaraf ah; I didn't even have the parameter in my config.

The not-actually-deleting problem is not resolved.
